model:
  name: 'resnet50_fc512'
  pretrained: True

data:
  type: 'image'
  sources: ['whaleshark']
  targets: ['whaleshark']
  height: 256
  width: 256
  combineall: False
  transforms: ['random_crop']
  save_dir: 'log/01_whaleshark_resnet50'


loss:
  name: 'triplet'
  triplet:
    weight_t: 1.
    weight_x: 1.
  softmax:
    label_smooth: True

sampler:
  num_instances: 6

train:
  optim: 'amsgrad'
  lr: 0.0003
  max_epoch: 60
  batch_size: 60
  fixbase_epoch: 5
  open_layers: ['classifier']
  lr_scheduler: 'single_step'
  stepsize: [100]

test:
  batch_size: 100
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: 10
  rerank: False
