model:
  name: 'resnet50_fc512'
  pretrained: True
  num_train_classes: 384

data:
  type: 'image'
  source: 'bear_face'
  height: 150
  width: 150
  transforms_train: ['blur','random_grayscale']
  version: 'v2'
  save_dir: '/data/log' 

loss:
  name: 'triplet'
  triplet:
    weight_t: 1.
    weight_x: 1.
  softmax:
    label_smooth: True

sampler:
  num_instances: 3
  num_copies: 3

train:
  optim: 'adam'
  lr: 0.00001
  max_epoch: 2000
  batch_size: 64
  fixbase_epoch: 1
  open_layers: ['fc', 'classifier']
  lr_scheduler: 'multi_step'
  stepsize: [1000]

test:
  batch_size: 64
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: 10
  rerank: False
  ranks: [1, 2, 3, 4, 5, 10, 15, 17]
  visrank_topk: 12
  visrank_resize: False
